const cosiness = [
	{ name: 'slide1', url: '/images/swiper-cosiness/1.jpeg' },
	{ name: 'slide2', url: '/images/swiper-cosiness/2.jpeg' },
	{ name: 'slide3', url: '/images/swiper-cosiness/3.jpeg' },
	{ name: 'slide4', url: '/images/swiper-cosiness/4.jpeg' },
	{ name: 'slide5', url: '/images/swiper-cosiness/5.jpeg' },
	{ name: 'slide6', url: '/images/swiper-cosiness/6.jpeg' },
	{ name: 'slide7', url: '/images/swiper-cosiness/7.jpeg' },
	{ name: 'slide8', url: '/images/swiper-cosiness/8.jpeg' },
	{ name: 'slide9', url: '/images/swiper-cosiness/9.jpeg' },
	{ name: 'slide10', url: '/images/swiper-cosiness/10.jpeg' },
	{ name: 'slide11', url: '/images/swiper-cosiness/11.jpeg' },
	{ name: 'slide12', url: '/images/swiper-cosiness/12.jpeg' },
	{ name: 'slide13', url: '/images/swiper-cosiness/13.jpeg' },
	{ name: 'slide14', url: '/images/swiper-cosiness/14.jpeg' },
	{ name: 'slide15', url: '/images/swiper-cosiness/15.jpeg' },
	{ name: 'slide16', url: '/images/swiper-cosiness/16.jpeg' },
	{ name: 'slide17', url: '/images/swiper-cosiness/17.jpeg' },
	{ name: 'slide18', url: '/images/swiper-cosiness/18.jpeg' },
	{ name: 'slide19', url: '/images/swiper-cosiness/19.jpeg' },
	{ name: 'slide20', url: '/images/swiper-cosiness/20.jpeg' },
	{ name: 'slide21', url: '/images/swiper-cosiness/21.jpeg' },
	{ name: 'slide22', url: '/images/swiper-cosiness/22.jpeg' },
	{ name: 'slide23', url: '/images/swiper-cosiness/23.jpeg' },
]

export default cosiness
